[package]
name = "struct-from-avro"
version = "0.1.3"
edition = "2021"
description= "Generate structs from avro schemas, you can specify the path of your avsc file on the program arguments"
license = "MIT"

[dependencies]
rsgen-avro = "0.11.2"